[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "15"
path = "15/1.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
