[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "21"
path = "21/2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
